spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/hotel
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=false

app.jwt.secret=05299dc1cf1a434f5ae495380e2a41af65b5959c941a71962a324ac5acf1b24b
app.jwt.expiration-ms=86400000

logging.level.root = INFO